ingress:
  # -- annotations for the ingress
  annotations: {}
  # -- enable the ingress
  enabled: true
  # -- host for the ingress
  host: localhost
  # -- tls configuration for the ingress
  tls: []
listmonk:
  image:
    # -- the listmonk image repository
    repository: listmonk/listmonk
    # -- the listmonk image tag
    tag: v4.0.1
  # -- the number of listmonk deployment replicas
  replicas: 1
postgres:
  # -- enable postgres
  enabled: true
  # -- when not enabled, the external postgress service hostname is required
  hostname: "listmonk"
  # -- the postgres database name
  database: listmonk
  image:
    # -- the postgres image repository
    repository: postgres
    # -- the postgres image tag
    tag: 16-alpine
  # -- the postgres password
  password: "listmonk"
  # -- resources configuration for the postgres statefulset
  resources: {}
  # -- the postgres username
  user: "listmonk"
