apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
data:
  config.toml: |
    [app]
    # Interface and port where the app will run its webserver.
      address = "0.0.0.0:80"

    # Database.
      [db]
      host = "{{- include "listmonk.fullname" .}}-postgres"
      port = 5432
      user = "{{ .Values.postgres.user}}"
      password = "{{ .Values.postgres.password }}"
      database = "{{ .Values.postgres.database }}"
      ssl_mode = "disable"
      max_open = 25
      max_idle = 25
      max_lifetime = "300s"
