apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.listmonk.replicas}}
  selector:
    matchLabels:
      deployment: listmonk
      {{- include "listmonk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: listmonk
        {{- include "listmonk.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: LISTMONK_db__user
          value: {{ .Values.postgres.user }}
        - name: LISTMONK_db__password
          value: {{ .Values.postgres.password }}
        image: {{ .Values.listmonk.image.repository }}:{{ .Values.listmonk.image.tag | default .Chart.AppVersion }}
        name: listmonk
        volumeMounts:
        - mountPath: /listmonk/config.toml
          name: config
          subPath: config.toml
      initContainers:
      - env:
        - name: LISTMONK_db__user
          value: {{ .Values.postgres.user }}
        - name: LISTMONK_db__password
          value: {{ .Values.postgres.password }}
        name: init
        image: {{ .Values.listmonk.image.repository }}:{{ .Values.listmonk.image.tag | default .Chart.AppVersion }}
        command:
        - ./listmonk
        - --install
        - --upgrade
        - --yes
        volumeMounts:
        - mountPath: /listmonk/config.toml
          name: config
          subPath: config.toml
      volumes:
      - configMap:
          name: {{ include "listmonk.fullname" . }}-listmonk
        name: config
