apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
  name: {{ include "listmonk.fullname" . }}-postgres
data:
  PASSWORD: {{ .Values.postgres.password | b64enc }}
  USER: {{ .Values.postgres.user | b64enc }}
