apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n.fullname" . }}-postgres
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  DATABASE: "{{ .Values.postgres.database}}"
  HOST: "{{ include "n8n.fullname" . }}-postgres"
  PORT: "5432"
