apiVersion: v1
data:
  DATABASE: "{{ .Values.postgres.database}}"
  HOST: "{{ include "n8n.fullname" . }}-postgres"
  PORT: "5432"
kind: ConfigMap
metadata:
  labels:
    {{ include "n8n.labels" . | nindent 4 }}
  name: {{ include "n8n.fullname" . }}-postgres
