apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "n8n.labels" . | nindent 4 }}
  name: {{ include "n8n.fullname" . }}-postgres
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    statefulSet: postgres
      {{ include "n8n.selectorLabels" . | nindent 4 }}
  type: ClusterIP
