apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-postgres
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    statefulSet: postgres
      {{- include "n8n.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
