apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-n8n
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    deployment: n8n
      {{- include "n8n.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 5678
    protocol: TCP
    targetPort: 5678
