ingress:
  # -- annotations for the ingress
  annotations: { }
  # -- enable the ingress
  enabled: false
  # -- hosts for the ingress
  hosts:
    - node-red.local
  # -- tls configuration for the ingress
  tls: [ ]
nodeRed:
  image:
    # -- node-red image repository
    repository: th0th/node-red
    # -- node-red image tag
    tag: null
  persistence:
    # -- enable persistence
    enabled: true
  # -- resources for the node-red statefulset
  resources: { }
  # -- node-red settings (settings.js in YAML format). please refer to https://nodered.org/docs/user-guide/runtime/configuration
  settings:
    # -- admin authentication config
    adminAuth:
      type: credentials
      # -- list of users
      users: [ ]
  #        - password: "$2y$08$q7DQYqhJrLC0.NnLelnre.IUaE2wQX3/xBiQ1cyAuNva8i5A6760q" // encrypted "changeme"
  #          permissions: "*"
  #          username: admin
    editorTheme:
      projects:
        enabled: false
  # -- time zone
  timeZone: America/New_York
