apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodeRed.fullname" . }}-node-red
  labels:
    {{- include "nodeRed.labels" . | nindent 4 }}
data:
  settings.js: |
    module.exports = {{ toJson .Values.nodeRed.settings }};
