apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodeRed.fullname" . }}-node-red
  labels:
    {{- include "nodeRed.labels" . | nindent 4 }}
data:
  settings.js: |
    module.exports = {
      adminAuth: {
        type: "{{ required "A valid .Values.nodeRed.settings.adminAuth.type is required!" .Values.nodeRed.settings.adminAuth.type }}",
        users: [
          {{- range (.Values.nodeRed.settings.adminAuth.users | default list) }}
            {
              password: "{{ .password }}",
              permissions: "{{ .permissions }}",
              username: "{{ .username }}",
            },
          {{- end }}
        ],
      },
    };
