{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nodeRed.fullname" . }}-node-red
  labels:
      {{- include "nodeRed.labels" . | nindent 4 }}
  annotations:
      {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - backend:
              service:
                name: '{{ include "nodeRed.fullname" . }}-node-red'
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
{{ end }}
