apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "ghost.labels" . | nindent 4 }}
  name: {{ include "ghost.fullname" . }}-mysql
data:
  PASSWORD: {{ required "A valid .Values.mysql.password is required" .Values.mysql.password | b64enc }}
  ROOT_PASSWORD: {{ required "A valid .Values.mysql.rootPassword is required" .Values.mysql.rootPassword | b64enc }}
  USER: {{ required "A valid .Values.mysql.user is required" .Values.mysql.user | b64enc }}
