apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "ghost.labels" . | nindent 4 }}
  name: {{ include "ghost.fullname" . }}-ghost
spec:
  type: ClusterIP
  selector:
    statefulSet: ghost
      {{ include "ghost.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 2368
    protocol: TCP
    targetPort: 2368
