apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "ghost.labels" . | nindent 4 }}
  name: {{ include "ghost.fullname" . }}-mysql
spec:
  type: ClusterIP
  selector:
    statefulSet: mysql
      {{ include "ghost.selectorLabels" . | nindent 4 }}
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
